name: Professional App — CI

on:
  push:
    branches: ["ci/**","main","master"]
  pull_request:
    branches: ["main","master"]
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests (app debug)
        run: ./gradlew :app:testDebugUnitTest --stacktrace

      - name: Build Debug APK (app)
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: List outputs (reports & apks)
        if: always()
        run: |
          echo "::group::Reports"
          ls -R app/build/reports/tests || true
          echo "::endgroup::"
          echo "::group::Test Results"
          ls -R app/build/test-results || true
          echo "::endgroup::"
          echo "::group::APKs"
          ls -R app/build/outputs/apk || true
          echo "::endgroup::"

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: professional-unit-test-reports
          path: |
            app/build/reports/tests/testDebugUnitTest/**
            app/build/test-results/testDebugUnitTest/**

      - name: Upload debug APK(s)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: professional-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
